//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetsHeroe.iOS.mx.com.petshero {
    using System.Xml.Serialization;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="wsPetsAppSoap", Namespace="http://www.petshero.com.mx")]
    public partial class wsPetsApp : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public AuthHeader AuthHeaderValue;
        
        private System.Threading.SendOrPostCallback ValidaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviaContrasenaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Pais_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Estado_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Ciudad_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CAM_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TipoAsociado_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TipoProducto_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MarcaProducto_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Producto_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Servicio_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Cliente_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Veterinario_RegistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback MascotaTipo_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MascotaRaza_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MascotaColor_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback MascotaEstatus_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Mascota_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Mascota_RegistroOperationCompleted;
        
        private System.Threading.SendOrPostCallback Mascota_IncidenteOperationCompleted;
        
        private System.Threading.SendOrPostCallback PuntosPromociones_BuscaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Codigo_ValidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback Codigo_LeidoOperationCompleted;
        
        private System.Threading.SendOrPostCallback Entrega_CAMOperationCompleted;
        
        private System.Threading.SendOrPostCallback Entrega_LocalizacionOperationCompleted;
        
        private System.Threading.SendOrPostCallback Entrega_SoloMensajeOperationCompleted;
        
        /// <remarks/>
        public wsPetsApp() {
            this.Url = "http://petshero.com.mx/webservices/wsPetsApp.asmx";
        }
        
        public wsPetsApp(string url) {
            this.Url = url;
        }
        
        /// <remarks/>
        public event ValidaUsuarioCompletedEventHandler ValidaUsuarioCompleted;
        
        /// <remarks/>
        public event EnviaContrasenaCompletedEventHandler EnviaContrasenaCompleted;
        
        /// <remarks/>
        public event Pais_BuscaCompletedEventHandler Pais_BuscaCompleted;
        
        /// <remarks/>
        public event Estado_BuscaCompletedEventHandler Estado_BuscaCompleted;
        
        /// <remarks/>
        public event Ciudad_BuscaCompletedEventHandler Ciudad_BuscaCompleted;
        
        /// <remarks/>
        public event CAM_BuscaCompletedEventHandler CAM_BuscaCompleted;
        
        /// <remarks/>
        public event TipoAsociado_BuscaCompletedEventHandler TipoAsociado_BuscaCompleted;
        
        /// <remarks/>
        public event TipoProducto_BuscaCompletedEventHandler TipoProducto_BuscaCompleted;
        
        /// <remarks/>
        public event MarcaProducto_BuscaCompletedEventHandler MarcaProducto_BuscaCompleted;
        
        /// <remarks/>
        public event Producto_BuscaCompletedEventHandler Producto_BuscaCompleted;
        
        /// <remarks/>
        public event Servicio_BuscaCompletedEventHandler Servicio_BuscaCompleted;
        
        /// <remarks/>
        public event Cliente_BuscaCompletedEventHandler Cliente_BuscaCompleted;
        
        /// <remarks/>
        public event Veterinario_RegistroCompletedEventHandler Veterinario_RegistroCompleted;
        
        /// <remarks/>
        public event MascotaTipo_BuscaCompletedEventHandler MascotaTipo_BuscaCompleted;
        
        /// <remarks/>
        public event MascotaRaza_BuscaCompletedEventHandler MascotaRaza_BuscaCompleted;
        
        /// <remarks/>
        public event MascotaColor_BuscaCompletedEventHandler MascotaColor_BuscaCompleted;
        
        /// <remarks/>
        public event MascotaEstatus_BuscaCompletedEventHandler MascotaEstatus_BuscaCompleted;
        
        /// <remarks/>
        public event Mascota_BuscaCompletedEventHandler Mascota_BuscaCompleted;
        
        /// <remarks/>
        public event Mascota_RegistroCompletedEventHandler Mascota_RegistroCompleted;
        
        /// <remarks/>
        public event Mascota_IncidenteCompletedEventHandler Mascota_IncidenteCompleted;
        
        /// <remarks/>
        public event PuntosPromociones_BuscaCompletedEventHandler PuntosPromociones_BuscaCompleted;
        
        /// <remarks/>
        public event Codigo_ValidaCompletedEventHandler Codigo_ValidaCompleted;
        
        /// <remarks/>
        public event Codigo_LeidoCompletedEventHandler Codigo_LeidoCompleted;
        
        /// <remarks/>
        public event Entrega_CAMCompletedEventHandler Entrega_CAMCompleted;
        
        /// <remarks/>
        public event Entrega_LocalizacionCompletedEventHandler Entrega_LocalizacionCompleted;
        
        /// <remarks/>
        public event Entrega_SoloMensajeCompletedEventHandler Entrega_SoloMensajeCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/ValidaUsuario", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool ValidaUsuario(string Usuario, string Contrasena, out int IDUsuario, out int IDMiembro, out int IDAsociado, out string Nombre) {
            object[] results = this.Invoke("ValidaUsuario", new object[] {
                        Usuario,
                        Contrasena});
            IDUsuario = ((int)(results[1]));
            IDMiembro = ((int)(results[2]));
            IDAsociado = ((int)(results[3]));
            Nombre = ((string)(results[4]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string Usuario, string Contrasena) {
            this.ValidaUsuarioAsync(Usuario, Contrasena, null);
        }
        
        /// <remarks/>
        public void ValidaUsuarioAsync(string Usuario, string Contrasena, object userState) {
            if ((this.ValidaUsuarioOperationCompleted == null)) {
                this.ValidaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnValidaUsuarioOperationCompleted);
            }
            this.InvokeAsync("ValidaUsuario", new object[] {
                        Usuario,
                        Contrasena}, this.ValidaUsuarioOperationCompleted, userState);
        }
        
        private void OnValidaUsuarioOperationCompleted(object arg) {
            if ((this.ValidaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ValidaUsuarioCompleted(this, new ValidaUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/EnviaContrasena", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void EnviaContrasena(string Usuario) {
            this.Invoke("EnviaContrasena", new object[] {
                        Usuario});
        }
        
        /// <remarks/>
        public void EnviaContrasenaAsync(string Usuario) {
            this.EnviaContrasenaAsync(Usuario, null);
        }
        
        /// <remarks/>
        public void EnviaContrasenaAsync(string Usuario, object userState) {
            if ((this.EnviaContrasenaOperationCompleted == null)) {
                this.EnviaContrasenaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviaContrasenaOperationCompleted);
            }
            this.InvokeAsync("EnviaContrasena", new object[] {
                        Usuario}, this.EnviaContrasenaOperationCompleted, userState);
        }
        
        private void OnEnviaContrasenaOperationCompleted(object arg) {
            if ((this.EnviaContrasenaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviaContrasenaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Pais_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Pais_Busca() {
            object[] results = this.Invoke("Pais_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Pais_BuscaAsync() {
            this.Pais_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void Pais_BuscaAsync(object userState) {
            if ((this.Pais_BuscaOperationCompleted == null)) {
                this.Pais_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPais_BuscaOperationCompleted);
            }
            this.InvokeAsync("Pais_Busca", new object[0], this.Pais_BuscaOperationCompleted, userState);
        }
        
        private void OnPais_BuscaOperationCompleted(object arg) {
            if ((this.Pais_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Pais_BuscaCompleted(this, new Pais_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Estado_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Estado_Busca(int IDPais) {
            object[] results = this.Invoke("Estado_Busca", new object[] {
                        IDPais});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Estado_BuscaAsync(int IDPais) {
            this.Estado_BuscaAsync(IDPais, null);
        }
        
        /// <remarks/>
        public void Estado_BuscaAsync(int IDPais, object userState) {
            if ((this.Estado_BuscaOperationCompleted == null)) {
                this.Estado_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEstado_BuscaOperationCompleted);
            }
            this.InvokeAsync("Estado_Busca", new object[] {
                        IDPais}, this.Estado_BuscaOperationCompleted, userState);
        }
        
        private void OnEstado_BuscaOperationCompleted(object arg) {
            if ((this.Estado_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Estado_BuscaCompleted(this, new Estado_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Ciudad_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Ciudad_Busca(int IDEstado) {
            object[] results = this.Invoke("Ciudad_Busca", new object[] {
                        IDEstado});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Ciudad_BuscaAsync(int IDEstado) {
            this.Ciudad_BuscaAsync(IDEstado, null);
        }
        
        /// <remarks/>
        public void Ciudad_BuscaAsync(int IDEstado, object userState) {
            if ((this.Ciudad_BuscaOperationCompleted == null)) {
                this.Ciudad_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCiudad_BuscaOperationCompleted);
            }
            this.InvokeAsync("Ciudad_Busca", new object[] {
                        IDEstado}, this.Ciudad_BuscaOperationCompleted, userState);
        }
        
        private void OnCiudad_BuscaOperationCompleted(object arg) {
            if ((this.Ciudad_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Ciudad_BuscaCompleted(this, new Ciudad_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/CAM_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable CAM_Busca(int IDPais, int IDEstado, int IDCiudad, int IDAsociado, double Latitud, double Longitud, double DistanciaKm) {
            object[] results = this.Invoke("CAM_Busca", new object[] {
                        IDPais,
                        IDEstado,
                        IDCiudad,
                        IDAsociado,
                        Latitud,
                        Longitud,
                        DistanciaKm});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void CAM_BuscaAsync(int IDPais, int IDEstado, int IDCiudad, int IDAsociado, double Latitud, double Longitud, double DistanciaKm) {
            this.CAM_BuscaAsync(IDPais, IDEstado, IDCiudad, IDAsociado, Latitud, Longitud, DistanciaKm, null);
        }
        
        /// <remarks/>
        public void CAM_BuscaAsync(int IDPais, int IDEstado, int IDCiudad, int IDAsociado, double Latitud, double Longitud, double DistanciaKm, object userState) {
            if ((this.CAM_BuscaOperationCompleted == null)) {
                this.CAM_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCAM_BuscaOperationCompleted);
            }
            this.InvokeAsync("CAM_Busca", new object[] {
                        IDPais,
                        IDEstado,
                        IDCiudad,
                        IDAsociado,
                        Latitud,
                        Longitud,
                        DistanciaKm}, this.CAM_BuscaOperationCompleted, userState);
        }
        
        private void OnCAM_BuscaOperationCompleted(object arg) {
            if ((this.CAM_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CAM_BuscaCompleted(this, new CAM_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/TipoAsociado_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TipoAsociado_Busca() {
            object[] results = this.Invoke("TipoAsociado_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TipoAsociado_BuscaAsync() {
            this.TipoAsociado_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void TipoAsociado_BuscaAsync(object userState) {
            if ((this.TipoAsociado_BuscaOperationCompleted == null)) {
                this.TipoAsociado_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTipoAsociado_BuscaOperationCompleted);
            }
            this.InvokeAsync("TipoAsociado_Busca", new object[0], this.TipoAsociado_BuscaOperationCompleted, userState);
        }
        
        private void OnTipoAsociado_BuscaOperationCompleted(object arg) {
            if ((this.TipoAsociado_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TipoAsociado_BuscaCompleted(this, new TipoAsociado_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/TipoProducto_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable TipoProducto_Busca() {
            object[] results = this.Invoke("TipoProducto_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void TipoProducto_BuscaAsync() {
            this.TipoProducto_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void TipoProducto_BuscaAsync(object userState) {
            if ((this.TipoProducto_BuscaOperationCompleted == null)) {
                this.TipoProducto_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTipoProducto_BuscaOperationCompleted);
            }
            this.InvokeAsync("TipoProducto_Busca", new object[0], this.TipoProducto_BuscaOperationCompleted, userState);
        }
        
        private void OnTipoProducto_BuscaOperationCompleted(object arg) {
            if ((this.TipoProducto_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TipoProducto_BuscaCompleted(this, new TipoProducto_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/MarcaProducto_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MarcaProducto_Busca() {
            object[] results = this.Invoke("MarcaProducto_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MarcaProducto_BuscaAsync() {
            this.MarcaProducto_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void MarcaProducto_BuscaAsync(object userState) {
            if ((this.MarcaProducto_BuscaOperationCompleted == null)) {
                this.MarcaProducto_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMarcaProducto_BuscaOperationCompleted);
            }
            this.InvokeAsync("MarcaProducto_Busca", new object[0], this.MarcaProducto_BuscaOperationCompleted, userState);
        }
        
        private void OnMarcaProducto_BuscaOperationCompleted(object arg) {
            if ((this.MarcaProducto_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MarcaProducto_BuscaCompleted(this, new MarcaProducto_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Producto_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Producto_Busca(int IDAsociado, int IDProducto, int IDTipoProducto, int IDMarca, string Nombre, string UPC, bool Promociones) {
            object[] results = this.Invoke("Producto_Busca", new object[] {
                        IDAsociado,
                        IDProducto,
                        IDTipoProducto,
                        IDMarca,
                        Nombre,
                        UPC,
                        Promociones});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Producto_BuscaAsync(int IDAsociado, int IDProducto, int IDTipoProducto, int IDMarca, string Nombre, string UPC, bool Promociones) {
            this.Producto_BuscaAsync(IDAsociado, IDProducto, IDTipoProducto, IDMarca, Nombre, UPC, Promociones, null);
        }
        
        /// <remarks/>
        public void Producto_BuscaAsync(int IDAsociado, int IDProducto, int IDTipoProducto, int IDMarca, string Nombre, string UPC, bool Promociones, object userState) {
            if ((this.Producto_BuscaOperationCompleted == null)) {
                this.Producto_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProducto_BuscaOperationCompleted);
            }
            this.InvokeAsync("Producto_Busca", new object[] {
                        IDAsociado,
                        IDProducto,
                        IDTipoProducto,
                        IDMarca,
                        Nombre,
                        UPC,
                        Promociones}, this.Producto_BuscaOperationCompleted, userState);
        }
        
        private void OnProducto_BuscaOperationCompleted(object arg) {
            if ((this.Producto_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Producto_BuscaCompleted(this, new Producto_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Servicio_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Servicio_Busca(int IDAsociado, int IDServicio, int IDTipoMascota, string Nombre, bool Promociones) {
            object[] results = this.Invoke("Servicio_Busca", new object[] {
                        IDAsociado,
                        IDServicio,
                        IDTipoMascota,
                        Nombre,
                        Promociones});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Servicio_BuscaAsync(int IDAsociado, int IDServicio, int IDTipoMascota, string Nombre, bool Promociones) {
            this.Servicio_BuscaAsync(IDAsociado, IDServicio, IDTipoMascota, Nombre, Promociones, null);
        }
        
        /// <remarks/>
        public void Servicio_BuscaAsync(int IDAsociado, int IDServicio, int IDTipoMascota, string Nombre, bool Promociones, object userState) {
            if ((this.Servicio_BuscaOperationCompleted == null)) {
                this.Servicio_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnServicio_BuscaOperationCompleted);
            }
            this.InvokeAsync("Servicio_Busca", new object[] {
                        IDAsociado,
                        IDServicio,
                        IDTipoMascota,
                        Nombre,
                        Promociones}, this.Servicio_BuscaOperationCompleted, userState);
        }
        
        private void OnServicio_BuscaOperationCompleted(object arg) {
            if ((this.Servicio_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Servicio_BuscaCompleted(this, new Servicio_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Cliente_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Cliente_Busca(int IDMiembro, int IDAsociado, int IDSucursal, string Codigo, string NombreCompleto, string Nombre, string Paterno, string Materno, string Sexo, string CorreoElectronico, string RFC) {
            object[] results = this.Invoke("Cliente_Busca", new object[] {
                        IDMiembro,
                        IDAsociado,
                        IDSucursal,
                        Codigo,
                        NombreCompleto,
                        Nombre,
                        Paterno,
                        Materno,
                        Sexo,
                        CorreoElectronico,
                        RFC});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Cliente_BuscaAsync(int IDMiembro, int IDAsociado, int IDSucursal, string Codigo, string NombreCompleto, string Nombre, string Paterno, string Materno, string Sexo, string CorreoElectronico, string RFC) {
            this.Cliente_BuscaAsync(IDMiembro, IDAsociado, IDSucursal, Codigo, NombreCompleto, Nombre, Paterno, Materno, Sexo, CorreoElectronico, RFC, null);
        }
        
        /// <remarks/>
        public void Cliente_BuscaAsync(int IDMiembro, int IDAsociado, int IDSucursal, string Codigo, string NombreCompleto, string Nombre, string Paterno, string Materno, string Sexo, string CorreoElectronico, string RFC, object userState) {
            if ((this.Cliente_BuscaOperationCompleted == null)) {
                this.Cliente_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCliente_BuscaOperationCompleted);
            }
            this.InvokeAsync("Cliente_Busca", new object[] {
                        IDMiembro,
                        IDAsociado,
                        IDSucursal,
                        Codigo,
                        NombreCompleto,
                        Nombre,
                        Paterno,
                        Materno,
                        Sexo,
                        CorreoElectronico,
                        RFC}, this.Cliente_BuscaOperationCompleted, userState);
        }
        
        private void OnCliente_BuscaOperationCompleted(object arg) {
            if ((this.Cliente_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Cliente_BuscaCompleted(this, new Cliente_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Veterinario_Registro", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Veterinario_Registro(string NombreComercial, string UsuarioNombre, string UsuarioPaterno, string UsuarioMaterno, char UsuarioSexo, string CorreoElectronico, string Contrasena, int IDTipoAsociado, out int IDAsociado) {
            object[] results = this.Invoke("Veterinario_Registro", new object[] {
                        NombreComercial,
                        UsuarioNombre,
                        UsuarioPaterno,
                        UsuarioMaterno,
                        UsuarioSexo,
                        CorreoElectronico,
                        Contrasena,
                        IDTipoAsociado});
            IDAsociado = ((int)(results[1]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Veterinario_RegistroAsync(string NombreComercial, string UsuarioNombre, string UsuarioPaterno, string UsuarioMaterno, char UsuarioSexo, string CorreoElectronico, string Contrasena, int IDTipoAsociado) {
            this.Veterinario_RegistroAsync(NombreComercial, UsuarioNombre, UsuarioPaterno, UsuarioMaterno, UsuarioSexo, CorreoElectronico, Contrasena, IDTipoAsociado, null);
        }
        
        /// <remarks/>
        public void Veterinario_RegistroAsync(string NombreComercial, string UsuarioNombre, string UsuarioPaterno, string UsuarioMaterno, char UsuarioSexo, string CorreoElectronico, string Contrasena, int IDTipoAsociado, object userState) {
            if ((this.Veterinario_RegistroOperationCompleted == null)) {
                this.Veterinario_RegistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVeterinario_RegistroOperationCompleted);
            }
            this.InvokeAsync("Veterinario_Registro", new object[] {
                        NombreComercial,
                        UsuarioNombre,
                        UsuarioPaterno,
                        UsuarioMaterno,
                        UsuarioSexo,
                        CorreoElectronico,
                        Contrasena,
                        IDTipoAsociado}, this.Veterinario_RegistroOperationCompleted, userState);
        }
        
        private void OnVeterinario_RegistroOperationCompleted(object arg) {
            if ((this.Veterinario_RegistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Veterinario_RegistroCompleted(this, new Veterinario_RegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/MascotaTipo_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MascotaTipo_Busca() {
            object[] results = this.Invoke("MascotaTipo_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MascotaTipo_BuscaAsync() {
            this.MascotaTipo_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void MascotaTipo_BuscaAsync(object userState) {
            if ((this.MascotaTipo_BuscaOperationCompleted == null)) {
                this.MascotaTipo_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascotaTipo_BuscaOperationCompleted);
            }
            this.InvokeAsync("MascotaTipo_Busca", new object[0], this.MascotaTipo_BuscaOperationCompleted, userState);
        }
        
        private void OnMascotaTipo_BuscaOperationCompleted(object arg) {
            if ((this.MascotaTipo_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MascotaTipo_BuscaCompleted(this, new MascotaTipo_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/MascotaRaza_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MascotaRaza_Busca(int IDTipo) {
            object[] results = this.Invoke("MascotaRaza_Busca", new object[] {
                        IDTipo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MascotaRaza_BuscaAsync(int IDTipo) {
            this.MascotaRaza_BuscaAsync(IDTipo, null);
        }
        
        /// <remarks/>
        public void MascotaRaza_BuscaAsync(int IDTipo, object userState) {
            if ((this.MascotaRaza_BuscaOperationCompleted == null)) {
                this.MascotaRaza_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascotaRaza_BuscaOperationCompleted);
            }
            this.InvokeAsync("MascotaRaza_Busca", new object[] {
                        IDTipo}, this.MascotaRaza_BuscaOperationCompleted, userState);
        }
        
        private void OnMascotaRaza_BuscaOperationCompleted(object arg) {
            if ((this.MascotaRaza_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MascotaRaza_BuscaCompleted(this, new MascotaRaza_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/MascotaColor_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MascotaColor_Busca(int IDTipo) {
            object[] results = this.Invoke("MascotaColor_Busca", new object[] {
                        IDTipo});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MascotaColor_BuscaAsync(int IDTipo) {
            this.MascotaColor_BuscaAsync(IDTipo, null);
        }
        
        /// <remarks/>
        public void MascotaColor_BuscaAsync(int IDTipo, object userState) {
            if ((this.MascotaColor_BuscaOperationCompleted == null)) {
                this.MascotaColor_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascotaColor_BuscaOperationCompleted);
            }
            this.InvokeAsync("MascotaColor_Busca", new object[] {
                        IDTipo}, this.MascotaColor_BuscaOperationCompleted, userState);
        }
        
        private void OnMascotaColor_BuscaOperationCompleted(object arg) {
            if ((this.MascotaColor_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MascotaColor_BuscaCompleted(this, new MascotaColor_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/MascotaEstatus_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MascotaEstatus_Busca() {
            object[] results = this.Invoke("MascotaEstatus_Busca", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MascotaEstatus_BuscaAsync() {
            this.MascotaEstatus_BuscaAsync(null);
        }
        
        /// <remarks/>
        public void MascotaEstatus_BuscaAsync(object userState) {
            if ((this.MascotaEstatus_BuscaOperationCompleted == null)) {
                this.MascotaEstatus_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascotaEstatus_BuscaOperationCompleted);
            }
            this.InvokeAsync("MascotaEstatus_Busca", new object[0], this.MascotaEstatus_BuscaOperationCompleted, userState);
        }
        
        private void OnMascotaEstatus_BuscaOperationCompleted(object arg) {
            if ((this.MascotaEstatus_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MascotaEstatus_BuscaCompleted(this, new MascotaEstatus_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Mascota_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable Mascota_Busca(int IDMascota, int IDTipoMascota, int IDEstatus, int IDRaza, int IDAsociado, int IDSucursal, int IDMiembro, string Nombre, string Codigo, string CodigoDueno) {
            object[] results = this.Invoke("Mascota_Busca", new object[] {
                        IDMascota,
                        IDTipoMascota,
                        IDEstatus,
                        IDRaza,
                        IDAsociado,
                        IDSucursal,
                        IDMiembro,
                        Nombre,
                        Codigo,
                        CodigoDueno});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void Mascota_BuscaAsync(int IDMascota, int IDTipoMascota, int IDEstatus, int IDRaza, int IDAsociado, int IDSucursal, int IDMiembro, string Nombre, string Codigo, string CodigoDueno) {
            this.Mascota_BuscaAsync(IDMascota, IDTipoMascota, IDEstatus, IDRaza, IDAsociado, IDSucursal, IDMiembro, Nombre, Codigo, CodigoDueno, null);
        }
        
        /// <remarks/>
        public void Mascota_BuscaAsync(int IDMascota, int IDTipoMascota, int IDEstatus, int IDRaza, int IDAsociado, int IDSucursal, int IDMiembro, string Nombre, string Codigo, string CodigoDueno, object userState) {
            if ((this.Mascota_BuscaOperationCompleted == null)) {
                this.Mascota_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascota_BuscaOperationCompleted);
            }
            this.InvokeAsync("Mascota_Busca", new object[] {
                        IDMascota,
                        IDTipoMascota,
                        IDEstatus,
                        IDRaza,
                        IDAsociado,
                        IDSucursal,
                        IDMiembro,
                        Nombre,
                        Codigo,
                        CodigoDueno}, this.Mascota_BuscaOperationCompleted, userState);
        }
        
        private void OnMascota_BuscaOperationCompleted(object arg) {
            if ((this.Mascota_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Mascota_BuscaCompleted(this, new Mascota_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Mascota_Registro", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Mascota_Registro(
                    string DuenoCodigo, 
                    string DuenoNombre, 
                    string DuenoPaterno, 
                    string DuenoMaterno, 
                    char DuenoSexo, 
                    string CorreoElectronico, 
                    string Contrasena, 
                    string MascotaCodigo, 
                    string MascotaNombre, 
                    char MascotaSexo, 
                    int IDTipoMascota, 
                    int IDRazaMascota, 
                    int IDColorMascota, 
                    int EdadMascota, 
                    out int IDMiembro, 
                    out int IDCodigo, 
                    out int IDMascota, 
                    out int IDEstatusCodigo) {
            object[] results = this.Invoke("Mascota_Registro", new object[] {
                        DuenoCodigo,
                        DuenoNombre,
                        DuenoPaterno,
                        DuenoMaterno,
                        DuenoSexo,
                        CorreoElectronico,
                        Contrasena,
                        MascotaCodigo,
                        MascotaNombre,
                        MascotaSexo,
                        IDTipoMascota,
                        IDRazaMascota,
                        IDColorMascota,
                        EdadMascota});
            IDMiembro = ((int)(results[1]));
            IDCodigo = ((int)(results[2]));
            IDMascota = ((int)(results[3]));
            IDEstatusCodigo = ((int)(results[4]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Mascota_RegistroAsync(string DuenoCodigo, string DuenoNombre, string DuenoPaterno, string DuenoMaterno, char DuenoSexo, string CorreoElectronico, string Contrasena, string MascotaCodigo, string MascotaNombre, char MascotaSexo, int IDTipoMascota, int IDRazaMascota, int IDColorMascota, int EdadMascota) {
            this.Mascota_RegistroAsync(DuenoCodigo, DuenoNombre, DuenoPaterno, DuenoMaterno, DuenoSexo, CorreoElectronico, Contrasena, MascotaCodigo, MascotaNombre, MascotaSexo, IDTipoMascota, IDRazaMascota, IDColorMascota, EdadMascota, null);
        }
        
        /// <remarks/>
        public void Mascota_RegistroAsync(string DuenoCodigo, string DuenoNombre, string DuenoPaterno, string DuenoMaterno, char DuenoSexo, string CorreoElectronico, string Contrasena, string MascotaCodigo, string MascotaNombre, char MascotaSexo, int IDTipoMascota, int IDRazaMascota, int IDColorMascota, int EdadMascota, object userState) {
            if ((this.Mascota_RegistroOperationCompleted == null)) {
                this.Mascota_RegistroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascota_RegistroOperationCompleted);
            }
            this.InvokeAsync("Mascota_Registro", new object[] {
                        DuenoCodigo,
                        DuenoNombre,
                        DuenoPaterno,
                        DuenoMaterno,
                        DuenoSexo,
                        CorreoElectronico,
                        Contrasena,
                        MascotaCodigo,
                        MascotaNombre,
                        MascotaSexo,
                        IDTipoMascota,
                        IDRazaMascota,
                        IDColorMascota,
                        EdadMascota}, this.Mascota_RegistroOperationCompleted, userState);
        }
        
        private void OnMascota_RegistroOperationCompleted(object arg) {
            if ((this.Mascota_RegistroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Mascota_RegistroCompleted(this, new Mascota_RegistroCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Mascota_Incidente", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Mascota_Incidente(int IDMascota, int IDTipoIncidente, int IDCanal, int IDCondicion, int IDTipoRetorno, int IDSucursal, string Notas) {
            this.Invoke("Mascota_Incidente", new object[] {
                        IDMascota,
                        IDTipoIncidente,
                        IDCanal,
                        IDCondicion,
                        IDTipoRetorno,
                        IDSucursal,
                        Notas});
        }
        
        /// <remarks/>
        public void Mascota_IncidenteAsync(int IDMascota, int IDTipoIncidente, int IDCanal, int IDCondicion, int IDTipoRetorno, int IDSucursal, string Notas) {
            this.Mascota_IncidenteAsync(IDMascota, IDTipoIncidente, IDCanal, IDCondicion, IDTipoRetorno, IDSucursal, Notas, null);
        }
        
        /// <remarks/>
        public void Mascota_IncidenteAsync(int IDMascota, int IDTipoIncidente, int IDCanal, int IDCondicion, int IDTipoRetorno, int IDSucursal, string Notas, object userState) {
            if ((this.Mascota_IncidenteOperationCompleted == null)) {
                this.Mascota_IncidenteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMascota_IncidenteOperationCompleted);
            }
            this.InvokeAsync("Mascota_Incidente", new object[] {
                        IDMascota,
                        IDTipoIncidente,
                        IDCanal,
                        IDCondicion,
                        IDTipoRetorno,
                        IDSucursal,
                        Notas}, this.Mascota_IncidenteOperationCompleted, userState);
        }
        
        private void OnMascota_IncidenteOperationCompleted(object arg) {
            if ((this.Mascota_IncidenteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Mascota_IncidenteCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/PuntosPromociones_Busca", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable PuntosPromociones_Busca(int IDMiembro, int IDMascota, int IDAsociado) {
            object[] results = this.Invoke("PuntosPromociones_Busca", new object[] {
                        IDMiembro,
                        IDMascota,
                        IDAsociado});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void PuntosPromociones_BuscaAsync(int IDMiembro, int IDMascota, int IDAsociado) {
            this.PuntosPromociones_BuscaAsync(IDMiembro, IDMascota, IDAsociado, null);
        }
        
        /// <remarks/>
        public void PuntosPromociones_BuscaAsync(int IDMiembro, int IDMascota, int IDAsociado, object userState) {
            if ((this.PuntosPromociones_BuscaOperationCompleted == null)) {
                this.PuntosPromociones_BuscaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPuntosPromociones_BuscaOperationCompleted);
            }
            this.InvokeAsync("PuntosPromociones_Busca", new object[] {
                        IDMiembro,
                        IDMascota,
                        IDAsociado}, this.PuntosPromociones_BuscaOperationCompleted, userState);
        }
        
        private void OnPuntosPromociones_BuscaOperationCompleted(object arg) {
            if ((this.PuntosPromociones_BuscaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PuntosPromociones_BuscaCompleted(this, new PuntosPromociones_BuscaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("AuthHeaderValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Codigo_Valida", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool Codigo_Valida(string Codigo, out int IDCodigo, out int IDEstatusCodigo, out int IDMascotaCodigo) {
            object[] results = this.Invoke("Codigo_Valida", new object[] {
                        Codigo});
            IDCodigo = ((int)(results[1]));
            IDEstatusCodigo = ((int)(results[2]));
            IDMascotaCodigo = ((int)(results[3]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void Codigo_ValidaAsync(string Codigo) {
            this.Codigo_ValidaAsync(Codigo, null);
        }
        
        /// <remarks/>
        public void Codigo_ValidaAsync(string Codigo, object userState) {
            if ((this.Codigo_ValidaOperationCompleted == null)) {
                this.Codigo_ValidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodigo_ValidaOperationCompleted);
            }
            this.InvokeAsync("Codigo_Valida", new object[] {
                        Codigo}, this.Codigo_ValidaOperationCompleted, userState);
        }
        
        private void OnCodigo_ValidaOperationCompleted(object arg) {
            if ((this.Codigo_ValidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Codigo_ValidaCompleted(this, new Codigo_ValidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Codigo_Leido", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Codigo_Leido(int IDCanal, string Codigo, double Latitud, double Longitud) {
            this.Invoke("Codigo_Leido", new object[] {
                        IDCanal,
                        Codigo,
                        Latitud,
                        Longitud});
        }
        
        /// <remarks/>
        public void Codigo_LeidoAsync(int IDCanal, string Codigo, double Latitud, double Longitud) {
            this.Codigo_LeidoAsync(IDCanal, Codigo, Latitud, Longitud, null);
        }
        
        /// <remarks/>
        public void Codigo_LeidoAsync(int IDCanal, string Codigo, double Latitud, double Longitud, object userState) {
            if ((this.Codigo_LeidoOperationCompleted == null)) {
                this.Codigo_LeidoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCodigo_LeidoOperationCompleted);
            }
            this.InvokeAsync("Codigo_Leido", new object[] {
                        IDCanal,
                        Codigo,
                        Latitud,
                        Longitud}, this.Codigo_LeidoOperationCompleted, userState);
        }
        
        private void OnCodigo_LeidoOperationCompleted(object arg) {
            if ((this.Codigo_LeidoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Codigo_LeidoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Entrega_CAM", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Entrega_CAM(int IDCanal, string Codigo, int IDSucursal, string Notas, double Latitud, double Longitud) {
            this.Invoke("Entrega_CAM", new object[] {
                        IDCanal,
                        Codigo,
                        IDSucursal,
                        Notas,
                        Latitud,
                        Longitud});
        }
        
        /// <remarks/>
        public void Entrega_CAMAsync(int IDCanal, string Codigo, int IDSucursal, string Notas, double Latitud, double Longitud) {
            this.Entrega_CAMAsync(IDCanal, Codigo, IDSucursal, Notas, Latitud, Longitud, null);
        }
        
        /// <remarks/>
        public void Entrega_CAMAsync(int IDCanal, string Codigo, int IDSucursal, string Notas, double Latitud, double Longitud, object userState) {
            if ((this.Entrega_CAMOperationCompleted == null)) {
                this.Entrega_CAMOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntrega_CAMOperationCompleted);
            }
            this.InvokeAsync("Entrega_CAM", new object[] {
                        IDCanal,
                        Codigo,
                        IDSucursal,
                        Notas,
                        Latitud,
                        Longitud}, this.Entrega_CAMOperationCompleted, userState);
        }
        
        private void OnEntrega_CAMOperationCompleted(object arg) {
            if ((this.Entrega_CAMCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Entrega_CAMCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Entrega_Localizacion", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Entrega_Localizacion(int IDCanal, string Codigo, int IDCiudad, string Nombre, string Correo, string Telefono, string Localizacion, string Notas, double Latitud, double Longitud) {
            this.Invoke("Entrega_Localizacion", new object[] {
                        IDCanal,
                        Codigo,
                        IDCiudad,
                        Nombre,
                        Correo,
                        Telefono,
                        Localizacion,
                        Notas,
                        Latitud,
                        Longitud});
        }
        
        /// <remarks/>
        public void Entrega_LocalizacionAsync(int IDCanal, string Codigo, int IDCiudad, string Nombre, string Correo, string Telefono, string Localizacion, string Notas, double Latitud, double Longitud) {
            this.Entrega_LocalizacionAsync(IDCanal, Codigo, IDCiudad, Nombre, Correo, Telefono, Localizacion, Notas, Latitud, Longitud, null);
        }
        
        /// <remarks/>
        public void Entrega_LocalizacionAsync(int IDCanal, string Codigo, int IDCiudad, string Nombre, string Correo, string Telefono, string Localizacion, string Notas, double Latitud, double Longitud, object userState) {
            if ((this.Entrega_LocalizacionOperationCompleted == null)) {
                this.Entrega_LocalizacionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntrega_LocalizacionOperationCompleted);
            }
            this.InvokeAsync("Entrega_Localizacion", new object[] {
                        IDCanal,
                        Codigo,
                        IDCiudad,
                        Nombre,
                        Correo,
                        Telefono,
                        Localizacion,
                        Notas,
                        Latitud,
                        Longitud}, this.Entrega_LocalizacionOperationCompleted, userState);
        }
        
        private void OnEntrega_LocalizacionOperationCompleted(object arg) {
            if ((this.Entrega_LocalizacionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Entrega_LocalizacionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.petshero.com.mx/Entrega_SoloMensaje", RequestNamespace="http://www.petshero.com.mx", ResponseNamespace="http://www.petshero.com.mx", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Entrega_SoloMensaje(int IDCanal, string Codigo, string Nombre, string Correo, string Telefono, string Mensaje, double Latitud, double Longitud) {
            this.Invoke("Entrega_SoloMensaje", new object[] {
                        IDCanal,
                        Codigo,
                        Nombre,
                        Correo,
                        Telefono,
                        Mensaje,
                        Latitud,
                        Longitud});
        }
        
        /// <remarks/>
        public void Entrega_SoloMensajeAsync(int IDCanal, string Codigo, string Nombre, string Correo, string Telefono, string Mensaje, double Latitud, double Longitud) {
            this.Entrega_SoloMensajeAsync(IDCanal, Codigo, Nombre, Correo, Telefono, Mensaje, Latitud, Longitud, null);
        }
        
        /// <remarks/>
        public void Entrega_SoloMensajeAsync(int IDCanal, string Codigo, string Nombre, string Correo, string Telefono, string Mensaje, double Latitud, double Longitud, object userState) {
            if ((this.Entrega_SoloMensajeOperationCompleted == null)) {
                this.Entrega_SoloMensajeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEntrega_SoloMensajeOperationCompleted);
            }
            this.InvokeAsync("Entrega_SoloMensaje", new object[] {
                        IDCanal,
                        Codigo,
                        Nombre,
                        Correo,
                        Telefono,
                        Mensaje,
                        Latitud,
                        Longitud}, this.Entrega_SoloMensajeOperationCompleted, userState);
        }
        
        private void OnEntrega_SoloMensajeOperationCompleted(object arg) {
            if ((this.Entrega_SoloMensajeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Entrega_SoloMensajeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.petshero.com.mx")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.petshero.com.mx", IsNullable=false)]
    public partial class AuthHeader : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string Usuario;
        
        /// <remarks/>
        public string Password;
        
        /// <remarks/>
        public int IDUsuario;
        
        /// <remarks/>
        public string IPAddress;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr;
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void ValidaUsuarioCompletedEventHandler(object sender, ValidaUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ValidaUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ValidaUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int IDUsuario {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int IDMiembro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int IDAsociado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public string Nombre {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void EnviaContrasenaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Pais_BuscaCompletedEventHandler(object sender, Pais_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Pais_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Pais_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Estado_BuscaCompletedEventHandler(object sender, Estado_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Estado_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Estado_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Ciudad_BuscaCompletedEventHandler(object sender, Ciudad_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Ciudad_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Ciudad_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void CAM_BuscaCompletedEventHandler(object sender, CAM_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CAM_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CAM_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void TipoAsociado_BuscaCompletedEventHandler(object sender, TipoAsociado_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TipoAsociado_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TipoAsociado_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void TipoProducto_BuscaCompletedEventHandler(object sender, TipoProducto_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TipoProducto_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TipoProducto_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void MarcaProducto_BuscaCompletedEventHandler(object sender, MarcaProducto_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MarcaProducto_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MarcaProducto_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Producto_BuscaCompletedEventHandler(object sender, Producto_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Producto_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Producto_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Servicio_BuscaCompletedEventHandler(object sender, Servicio_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Servicio_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Servicio_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Cliente_BuscaCompletedEventHandler(object sender, Cliente_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Cliente_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Cliente_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Veterinario_RegistroCompletedEventHandler(object sender, Veterinario_RegistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Veterinario_RegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Veterinario_RegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int IDAsociado {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void MascotaTipo_BuscaCompletedEventHandler(object sender, MascotaTipo_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MascotaTipo_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MascotaTipo_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void MascotaRaza_BuscaCompletedEventHandler(object sender, MascotaRaza_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MascotaRaza_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MascotaRaza_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void MascotaColor_BuscaCompletedEventHandler(object sender, MascotaColor_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MascotaColor_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MascotaColor_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void MascotaEstatus_BuscaCompletedEventHandler(object sender, MascotaEstatus_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MascotaEstatus_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MascotaEstatus_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Mascota_BuscaCompletedEventHandler(object sender, Mascota_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mascota_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Mascota_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Mascota_RegistroCompletedEventHandler(object sender, Mascota_RegistroCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Mascota_RegistroCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Mascota_RegistroCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int IDMiembro {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int IDCodigo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int IDMascota {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
        
        /// <remarks/>
        public int IDEstatusCodigo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[4]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Mascota_IncidenteCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void PuntosPromociones_BuscaCompletedEventHandler(object sender, PuntosPromociones_BuscaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PuntosPromociones_BuscaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PuntosPromociones_BuscaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Codigo_ValidaCompletedEventHandler(object sender, Codigo_ValidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Codigo_ValidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Codigo_ValidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public int IDCodigo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int IDEstatusCodigo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
        
        /// <remarks/>
        public int IDMascotaCodigo {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[3]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Codigo_LeidoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Entrega_CAMCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Entrega_LocalizacionCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XamarinStudio", "8.2.6.26")]
    public delegate void Entrega_SoloMensajeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}
